### ISSUE TITLE
Activating extension failed: cannot find module 'dateFormat'

### ISSUE THREAD

**Issue by bgse** [zabel-xyz/plsql-language#15]
VSCode: 1.11.2
OS: Linux Ubuntu 16.04

Extension doesn't load properly, see developer console:

![extension_loadfail](https://cloud.githubusercontent.com/assets/8385202/25659830/d4a92c24-3009-11e7-82b0-474da1ceaf50.png)

Didn't have time to dig into it myself, but could this simply be an upper/lower case issue?

**Comment by zabel-xyz** [comment]
You are right. It's probably an upper/lower case issue, but I can't test on Linux  (On Windows, both case work).
I think there is a problem in this file:
.vscode\extensions\xyz.plsql-language-1.0.2\out\src\pldoc.controller.js
to fix the case issue, try to change this line :
const dateFormat = require("dateformat");

I'll make an update...

**Comment by zabel-xyz** [comment]
try with version 1.0.3

**Comment by bgse** [comment]
Working on Linux as of 1.0.3, thank you for the update.

Closing the issue.
